image: harbor.hb.dfki.de/hyrodyn/hyrodyn-ci:ubuntu22

workflow:
  rules:
    - changes:
        - README.md
        - bin/**/* 
        - doc/**/* 
        - docker/**/*
        - python/**/* 
        - robot/**/* 
      when: never
    - when: always

stages:
  - build
  - test
  - deploy

variables:
  BUILD_DIR: build
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: -1

build:
  stage: build
  script:
    - cmake -S . -B $BUILD_DIR -DBUILD_TESTING=ON
    - cmake --build $BUILD_DIR --parallel
  artifacts:
    paths:
      - $BUILD_DIR
    expire_in: 1 hour

test:
  stage: test
  script:
    # IMPORTANT: run tests from PROJECT ROOT
    - ./build/test/hyrodyn_tests
  needs:
    - job: build

deploy:
  stage: deploy
  script:
    - cmake --install $BUILD_DIR --prefix install
  artifacts:
    paths:
      - install/
    expire_in: 7 days
  needs:
    - job: build
