import hyrodyn 
import time 
import numpy as np 
import os 
import argparse
from argparse import RawTextHelpFormatter
from urdfpy import URDF

def main (path_to_urdf, path_to_submechamisms, body_name):
	"""Return the print-outs as a dictionary
	----- Parameters -----
	path_to_urdf, path_to_submechamisms : strings
	pathes to the urdf and submechanism files
	Returns
	dict_zero_config, dict_joint_config : dictionaries
	dictionary of the zero configuration and the joint configuration
	"""
	# Path to URDF and Submechanism.yml files 
	path_to_urdf =  os.environ["AUTOPROJ_CURRENT_ROOT"] + path_to_urdf
	path_to_submechamisms = os.environ["AUTOPROJ_CURRENT_ROOT"] + path_to_submechamisms

	# Load the robot model in HyRoDyn
	robot = hyrodyn.RobotModel(path_to_urdf, path_to_submechamisms)

	# Information of different joints in the robot
	active_joints = robot.jointnames_active
	independent_joints = robot.jointnames_independent
	spanning_tree_joints = robot.jointnames_spanningtree
	print("Names of active joints: ", active_joints)
	print("Names of independent joints: ", independent_joints)
	print("Names of spanning tree joints: ", spanning_tree_joints)

	# Compute the COM properties of the robot in zero configuration
	robot.calculate_com_properties()
	print("Total moving mass in zero config = ",robot.mass)
	print("COM in zero config = ",robot.com)

	# Compute full state of the spanning tree
	robot.calculate_system_state()
	print("Spanning tree joint positions (all the joints in the robot): ", robot.Q)
	print("Actuator joint positions (subset of spanning tree joints): ", robot.u)

	# Forward Kinematics
	robot.calculate_forward_kinematics(body_name)
	print("Forward kinematics of the body " + body_name + " ([X Y Z Qx Qy Qz Qw]):", robot.pose)

	# Inverse dynamics
	robot.calculate_inverse_dynamics()
	print("Inverse dynamics output: ", robot.Tau_actuated)

	# Visualize the robot
	keys = robot.jointnames_spanningtree
	values = robot.Q[0].tolist()
	config_dict = dict(zip(keys, values))
	print(config_dict)

	active_dof  = len(active_joints)
	independent_joints_dof = len(independent_joints)
	spanning_tree_joints_dof = len(spanning_tree_joints)
	dict_zero_config = {"Mass of the robot": {"Total moving mass in zero configuration": str(robot.mass), "Centre of mass in zero configuration": str(robot.com)}, "Kinematics and dynamics": {"Forward kinematics": str(robot.pose), "Inverse dynamics": str(robot.Tau_actuated)}, "Names and degrees of freedom": {"Active joints": {"Names": active_joints, "DOF": active_dof} , "Independent joints": {"Names": independent_joints, "DOF": independent_joints_dof}, "Spanning tree joints": {"Names": spanning_tree_joints, "DOF": spanning_tree_joints_dof}},"Joint positions": {"Positions of all joints of the robot": str(robot.Q), "Positions of the actuator joints": str(robot.u)}}
	return dict_zero_config
	

if __name__ == '__main__':

	# Create the parser
	parser = argparse.ArgumentParser(description = "Generate a analysis of the robot's zero configuration using HyRoDyn. Robot model in HyRoDyn is built using the URDF and submechanisms yaml file. The program extracts the coordinates of the workspace points from csv file generated by hyrodyn_analyze_robot C++ program (make sure it is available by building it) provided in applications/robot_analysis folder. The joint limits described in a yaml file (in RoCK convention) is used to discretize the input joint space. \n\nBasic Usage Example of the RH5 leg: \n\npython3 analyze_zero_config.py /control/hyrodyn/data/hybrid/rh5/leg/urdf/leg.urdf /control/hyrodyn/data/hybrid/rh5/leg/urdf/submechanisms.yml LLAnklePitch_Link \n\nBasic Usage Example of Recupera right arm: \n\npython3 analyze_zero_config.py /control/hyrodyn/data/hybrid/recupera/right_arm_teleop/urdf/right_arm_teleop.urdf /control/hyrodyn/data/hybrid/recupera/right_arm_teleop/urdf/submechanisms.yml right_exo_elbow", formatter_class=RawTextHelpFormatter)

	# Add the arguments
	parser.add_argument("urdf_path", type = str,
		            help="URDF path for the robot with respect to AUTOPROJ_CURRENT_ROOT")
	parser.add_argument("submechanism_yml", type = str, 
		            help="YAML file describing the submechanisms with respect to AUTOPROJ_CURRENT_ROOT")
	parser.add_argument("body_name", type = str,
		            help="Name of the part of the robot's body which should be visualized")

	# Execute the parse_args method
	args, unknown = parser.parse_known_args()
	
	# Store the variables in the args
	path_to_urdf = args.urdf_path
	path_to_submechamisms = args.submechanism_yml
	body_name = args.body_name

	# Call the main function
	main(path_to_urdf, path_to_submechamisms, body_name)

